package lps.bet.basico.gui;

import lps.bet.basico.catraca.CatracaEvent;
import lps.bet.basico.catraca.CatracaListener;
import lps.bet.basico.catraca.IGirarCatraca;
import lps.bet.basico.leitoraCartao.ILeitora;
import lps.bet.basico.visor.IVisor;
import lps.bet.basico.visor.VisorEvent;
import lps.bet.basico.visor.VisorListener;

import org.springframework.beans.factory.BeanFactory;
import org.springframework.beans.factory.xml.XmlBeanFactory;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;

public class ValidadorGUI extends javax.swing.JFrame implements VisorListener, CatracaListener{
	    
		private IGirarCatraca interfaceGirarCatraca;
		private ILeitora interfaceLeitora;
		private IVisor interfaceVisor;
	
	    public IVisor getInterfaceVisor() {
			return interfaceVisor;
		}

		public void setInterfaceVisor(IVisor interfaceVisor) {
			this.interfaceVisor = interfaceVisor;
		}

		/** Creates new form FormularioJFrame */
	    public ValidadorGUI(IGirarCatraca interfaceGirarCatraca, IVisor interfaceVisor) {
	    	this.interfaceGirarCatraca = interfaceGirarCatraca;
	    	this.interfaceVisor = interfaceVisor;
	    	addListeners();
	        initComponents();
	    }

	    private void addListeners(){
	        interfaceGirarCatraca.addCatracaListener(this);
	        interfaceVisor.addVisorListener(this);
	    }
	    
	    public void catracaLiberada(CatracaEvent e) {
			//Habilitar botão de Girar Catraca
	    	girarCatracaButton.setEnabled(true);
		}

		public void novaMensagem(VisorEvent e) {
			visorTextArea.setText(e.getMensagem());			
		}

		/** This method is called from within the constructor to
	     * initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is
	     * always regenerated by the Form Editor.
	     */
	    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">                          
	    private void initComponents() {
	        leitoraCartaoLabel = new javax.swing.JLabel();
	        passarCartaoButton = new javax.swing.JButton();
	        numeroCartaoField = new javax.swing.JTextField();
	        girarCatracaButton = new javax.swing.JButton();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        visorTextArea = new javax.swing.JTextArea();
	        TituloLabel = new javax.swing.JLabel();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        leitoraCartaoLabel.setText("Leitora Cart\u00e3o:");

	        
	        
	        passarCartaoButton.setText("Passar Cartao");
	        passarCartaoButton.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                passarCartaoButtonActionPerformed(evt);
	            }
	        });

	        girarCatracaButton.setText("Girar Catraca");
	        girarCatracaButton.setEnabled(false);
	        girarCatracaButton.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                girarCatracaButtonActionPerformed(evt);
	            }
	        });

	        visorTextArea.setColumns(20);
	        visorTextArea.setRows(5);
	        jScrollPane1.setViewportView(visorTextArea);

	        TituloLabel.setText("Simulador do Validador do \u00d4nibus");

	        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(layout.createSequentialGroup()
	                .add(31, 31, 31)
	                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	                    .add(org.jdesktop.layout.GroupLayout.TRAILING, TituloLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
	                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
	                    .add(girarCatracaButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
	                    .add(layout.createSequentialGroup()
	                        .add(leitoraCartaoLabel)
	                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	                        .add(numeroCartaoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	                        .add(passarCartaoButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
	                .add(39, 39, 39))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(layout.createSequentialGroup()
	                .addContainerGap()
	                .add(TituloLabel)
	                .add(26, 26, 26)
	                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
	                    .add(leitoraCartaoLabel)
	                    .add(numeroCartaoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
	                    .add(passarCartaoButton))
	                .add(17, 17, 17)
	                .add(girarCatracaButton)
	                .add(15, 15, 15)
	                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
	                .addContainerGap())
	        );
	        pack();
	    }// </editor-fold>                        

	    private void girarCatracaButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
	    	interfaceGirarCatraca.girarCatraca();
	    	girarCatracaButton.setEnabled(false);
	    }                                                  

	    private void passarCartaoButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
	    	interfaceLeitora.passarCartao(numeroCartaoField.getText().trim());
	    }                                                  
	    
	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	        		Resource resource = new FileSystemResource("C:\\Documents and Settings\\Paula\\workspace\\bet\\src\\main\\resources\\onibus-context.xml");
	        		BeanFactory factory = new XmlBeanFactory(resource);
	        		ValidadorGUI validadorGUI = (ValidadorGUI) factory.getBean("Gui");
	            	validadorGUI.setVisible(true);
	            }
	        });
	    }
	    
	    // Declaração de variáveis - não modifique                     
	    private javax.swing.JLabel TituloLabel;
	    private javax.swing.JButton girarCatracaButton;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JLabel leitoraCartaoLabel;
	    private javax.swing.JTextField numeroCartaoField;
	    private javax.swing.JButton passarCartaoButton;
	    private javax.swing.JTextArea visorTextArea;
	    // Fim da declaração de variáveis                   

		public IGirarCatraca getInterfaceGirarCatraca() {
			return interfaceGirarCatraca;
		}

		public void setInterfaceGirarCatraca(IGirarCatraca interfaceGirarCatraca) {
			this.interfaceGirarCatraca = interfaceGirarCatraca;
		}

		public ILeitora getInterfaceLeitora() {
			return interfaceLeitora;
		}

		public void setInterfaceLeitora(ILeitora interfaceLeitora) {
			this.interfaceLeitora = interfaceLeitora;
		}         
}


